Friend Module GameStates
    Friend Const ChangePace = "ChangePace"
    Friend Const ConfirmAbandon = "ConfirmAbandon"
    Friend Const ConfirmQuit = "ConfirmQuit"
    Friend Const Dead = "Dead"
    Friend Const EatSnax = "EatSnax"
    Friend Const Embark = "Embark"
    Friend Const Forage = "Forage"
    Friend Const GameMenu = "GameMenu"
    Friend Const KeepGoing = "KeepGoing"
    Friend Const Load = "Load"
    Friend Const MainMenu = "MainMenu"
    Friend Const Neutral = "Neutral"
    Friend Const Options = "Options"
    Friend Const Save = "Save"
    Friend Const ScreenSize = "ScreenSize"
    Friend Const TakeShortcut = "TakeShortcut"
    Friend Const Volume = "Volume"
    Friend Const Win = "Win"
End Module
